#!/usr/bin/python3.7
import pandas as pd
import numpy as np
import click

@click.command()
@click.option('-d', "--directory", help="directory")
@click.option('-p', "--points", default="", help="points to generate statistics on")
def read_datasets(points, directory, file_location="/home/ejuzovitski/Documents/" +
                  "master_thesis/repos/ewkm/clusters/"):
    arr = np.fromstring(points, dtype=int, sep=' ')
    for i in arr:
        returnable_data = pd.read_json(
            path_or_buf=file_location+directory+"/"+str(i)+".json", lines=True)
        print("--------------")
        print(f'cluster {i}')
        print(returnable_data['genres'].value_counts())
        print(returnable_data['energies'].value_counts())
        print(returnable_data['bpm'].median())


read_datasets()
